class Countries:
    countries = [
        "Afghanistan",
        "Albania",
        "Algeria",
        "American Samoa",
        "Andorra",
        "Angola",
        "Anguilla",
        "Antarctica",
        "Antigua & Barbuda",
        "Argentina",
        "Armenia",
        "Aruba",
        "Australia",
        "Austria",
        "Azerbaijan",
        "Bahamas",
        "Bahrain",
        "Bangladesh",
        "Barbados",
        "Belarus",
        "Belgium",
        "Belize",
        "Benin",
        "Bermuda",
        "Bhutan",
        "Bolivia",
        "Bosnia & Herzegovina",
        "Botswana",
        "Bouvet Island",
        "Brazil",
        "British Indian Ocean Territory",
        "British Virgin Islands",
        "Brunei",
        "Bulgaria",
        "Burkina Faso",
        "Burundi",
        "Cambodia",
        "Cameroon",
        "Canada",
        "Cape Verde",
        "Caribbean Netherlands",
        "Cayman Islands",
        "Central African Republic",
        "Chad",
        "Chile",
        "China",
        "Christmas Island",
        "Cocos (Keeling) Islands",
        "Colombia",
        "Comoros",
        "Congo - Brazzaville",
        "Congo - Kinshasa",
        "Cook Islands",
        "Costa Rica",
        "Croatia",
        "Cuba",
        "Curaçao",
        "Cyprus",
        "Czechia",
        "Côte d’Ivoire",
        "Denmark",
        "Djibouti",
        "Dominica",
        "Dominican Republic",
        "Ecuador",
        "Egypt",
        "El Salvador",
        "Equatorial Guinea",
        "Eritrea",
        "Estonia",
        "Eswatini",
        "Ethiopia",
        "Falkland Islands (Islas Malvinas)",
        "Faroe Islands",
        "Fiji",
        "Finland",
        "France",
        "French Guiana",
        "French Polynesia",
        "French Southern Territories",
        "Gabon",
        "Gambia",
        "Georgia",
        "Germany",
        "Ghana",
        "Gibraltar",
        "Greece",
        "Greenland",
        "Grenada",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guernsey",
        "Guinea",
        "Guinea-Bissau",
        "Guyana",
        "Haiti",
        "Heard & McDonald Islands",
        "Honduras",
        "Hong Kong",
        "Hungary",
        "Iceland",
        "India",
        "Indonesia",
        "Iran",
        "Iraq",
        "Ireland",
        "Isle of Man",
        "Israel",
        "Italy",
        "Jamaica",
        "Japan",
        "Jersey",
        "Jordan",
        "Kazakhstan",
        "Kenya",
        "Kiribati",
        "Kosovo",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Latvia",
        "Lebanon",
        "Lesotho",
        "Liberia",
        "Libya",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Macao",
        "Madagascar",
        "Malawi",
        "Malaysia",
        "Maldives",
        "Mali",
        "Malta",
        "Marshall Islands",
        "Martinique",
        "Mauritania",
        "Mauritius",
        "Mayotte",
        "Mexico",
        "Micronesia",
        "Moldova",
        "Monaco",
        "Mongolia",
        "Montenegro",
        "Montserrat",
        "Morocco",
        "Mozambique",
        "Myanmar (Burma)",
        "Namibia",
        "Nauru",
        "Nepal",
        "Netherlands",
        "New Caledonia",
        "New Zealand",
        "Nicaragua",
        "Niger",
        "Nigeria",
        "Niue",
        "Norfolk Island",
        "North Korea",
        "North Macedonia",
        "Northern Mariana Islands",
        "Norway",
        "Oman",
        "Pakistan",
        "Palau",
        "Palestine",
        "Panama",
        "Papua New Guinea",
        "Paraguay",
        "Peru",
        "Philippines",
        "Pitcairn Islands",
        "Poland",
        "Portugal",
        "Puerto Rico",
        "Qatar",
        "Romania",
        "Russia",
        "Rwanda",
        "Réunion",
        "Samoa",
        "San Marino",
        "Saudi Arabia",
        "Senegal",
        "Serbia",
        "Seychelles",
        "Sierra Leone",
        "Singapore",
        "Sint Maarten",
        "Slovakia",
        "Slovenia",
        "Solomon Islands",
        "Somalia",
        "South Africa",
        "South Georgia & South Sandwich Islands",
        "South Korea",
        "South Sudan",
        "Spain",
        "Sri Lanka",
        "St. Barthélemy",
        "St. Helena",
        "St. Kitts & Nevis",
        "St. Lucia",
        "St. Martin",
        "St. Pierre & Miquelon",
        "St. Vincent & Grenadines",
        "Sudan",
        "Suriname",
        "Svalbard & Jan Mayen",
        "Sweden",
        "Switzerland",
        "Syria",
        "São Tomé & Príncipe",
        "Taiwan",
        "Tajikistan",
        "Tanzania",
        "Thailand",
        "Timor-Leste",
        "Togo",
        "Tokelau",
        "Tonga",
        "Trinidad & Tobago",
        "Tunisia",
        "Turkmenistan",
        "Turks & Caicos Islands",
        "Tuvalu",
        "Türkiye",
        "U.S. Outlying Islands",
        "U.S. Virgin Islands",
        "Uganda",
        "Ukraine",
        "United Arab Emirates",
        "United Kingdom",
        "United States",
        "Uruguay",
        "Uzbekistan",
        "Vanuatu",
        "Vatican City",
        "Venezuela",
        "Vietnam",
        "Wallis & Futuna",
        "Western Sahara",
        "Yemen",
        "Zambia",
        "Zimbabwe",
        "Åland Islands"
    ]

    country_to_iso = {
        "Afghanistan": "AFG",
        "Albania": "ALB",
        "Algeria": "DZA",
        "American Samoa": "ASM",
        "Andorra": "AND",
        "Angola": "AGO",
        "Anguilla": "AIA",
        "Antarctica": "ATA",
        "Antigua & Barbuda": "ATG",
        "Argentina": "ARG",
        "Armenia": "ARM",
        "Aruba": "ABW",
        "Australia": "AUS",
        "Austria": "AUT",
        "Azerbaijan": "AZE",
        "Bahamas": "BHS",
        "Bahrain": "BHR",
        "Bangladesh": "BGD",
        "Barbados": "BRB",
        "Belarus": "BLR",
        "Belgium": "BEL",
        "Belize": "BLZ",
        "Benin": "BEN",
        "Bermuda": "BMU",
        "Bhutan": "BTN",
        "Bolivia": "BOL",
        "Bosnia & Herzegovina": "BIH",
        "Botswana": "BWA",
        "Bouvet Island": "BVT",
        "Brazil": "BRA",
        "British Indian Ocean Territory": "IOT",
        "British Virgin Islands": "VGB",
        "Brunei": "BRN",
        "Bulgaria": "BGR",
        "Burkina Faso": "BFA",
        "Burundi": "BDI",
        "Cambodia": "KHM",
        "Cameroon": "CMR",
        "Canada": "CAN",
        "Cape Verde": "CPV",
        "Caribbean Netherlands": "BES",
        "Cayman Islands": "CYM",
        "Central African Republic": "CAF",
        "Chad": "TCD",
        "Chile": "CHL",
        "China": "CHN",
        "Christmas Island": "CXR",
        "Cocos (Keeling) Islands": "CCK",
        "Colombia": "COL",
        "Comoros": "COM",
        "Congo - Brazzaville": "COG",
        "Congo - Kinshasa": "COD",
        "Cook Islands": "COK",
        "Costa Rica": "CRI",
        "Croatia": "HRV",
        "Cuba": "CUB",
        "Curaçao": "CUW",
        "Cyprus": "CYP",
        "Czechia": "CZE",
        "Côte d’Ivoire": "CIV",
        "Denmark": "DNK",
        "Djibouti": "DJI",
        "Dominica": "DMA",
        "Dominican Republic": "DOM",
        "Ecuador": "ECU",
        "Egypt": "EGY",
        "El Salvador": "SLV",
        "Equatorial Guinea": "GNQ",
        "Eritrea": "ERI",
        "Estonia": "EST",
        "Eswatini": "SWZ",
        "Ethiopia": "ETH",
        "Falkland Islands (Islas Malvinas)": "FLK",
        "Faroe Islands": "FRO",
        "Fiji": "FJI",
        "Finland": "FIN",
        "France": "FRA",
        "French Guiana": "GUF",
        "French Polynesia": "PYF",
        "French Southern Territories": "ATF",
        "Gabon": "GAB",
        "Gambia": "GMB",
        "Georgia": "GEO",
        "Germany": "DEU",
        "Ghana": "GHA",
        "Gibraltar": "GIB",
        "Greece": "GRC",
        "Greenland": "GRL",
        "Grenada": "GRD",
        "Guadeloupe": "GLP",
        "Guam": "GUM",
        "Guatemala": "GTM",
        "Guernsey": "GGY",
        "Guinea": "GIN",
        "Guinea-Bissau": "GNB",
        "Guyana": "GUY",
        "Haiti": "HTI",
        "Heard & McDonald Islands": "HMD",
        "Honduras": "HND",
        "Hong Kong": "HKG",
        "Hungary": "HUN",
        "Iceland": "ISL",
        "India": "IND",
        "Indonesia": "IDN",
        "Iran": "IRN",
        "Iraq": "IRQ",
        "Ireland": "IRL",
        "Isle of Man": "IMN",
        "Israel": "ISR",
        "Italy": "ITA",
        "Jamaica": "JAM",
        "Japan": "JPN",
        "Jersey": "JEY",
        "Jordan": "JOR",
        "Kazakhstan": "KAZ",
        "Kenya": "KEN",
        "Kiribati": "KIR",
        "Kosovo": "XKX",
        "Kuwait": "KWT",
        "Kyrgyzstan": "KGZ",
        "Laos": "LAO",
        "Latvia": "LVA",
        "Lebanon": "LBN",
        "Lesotho": "LSO",
        "Liberia": "LBR",
        "Libya": "LBY",
        "Liechtenstein": "LIE",
        "Lithuania": "LTU",
        "Luxembourg": "LUX",
        "Macao": "MAC",
        "Madagascar": "MDG",
        "Malawi": "MWI",
        "Malaysia": "MYS",
        "Maldives": "MDV",
        "Mali": "MLI",
        "Malta": "MLT",
        "Marshall Islands": "MHL",
        "Martinique": "MTQ",
        "Mauritania": "MRT",
        "Mauritius": "MUS",
        "Mayotte": "MYT",
        "Mexico": "MEX",
        "Micronesia": "FSM",
        "Moldova": "MDA",
        "Monaco": "MCO",
        "Mongolia": "MNG",
        "Montenegro": "MNE",
        "Montserrat": "MSR",
        "Morocco": "MAR",
        "Mozambique": "MOZ",
        "Myanmar (Burma)": "MMR",
        "Namibia": "NAM",
        "Nauru": "NRU",
        "Nepal": "NPL",
        "Netherlands": "NLD",
        "New Caledonia": "NCL",
        "New Zealand": "NZL",
        "Nicaragua": "NIC",
        "Niger": "NER",
        "Nigeria": "NGA",
        "Niue": "NIU",
        "Norfolk Island": "NFK",
        "North Korea": "PRK",
        "North Macedonia": "MKD",
        "Northern Mariana Islands": "MNP",
        "Norway": "NOR",
        "Oman": "OMN",
        "Pakistan": "PAK",
        "Palau": "PLW",
        "Palestine": "PSE",
        "Panama": "PAN",
        "Papua New Guinea": "PNG",
        "Paraguay": "PRY",
        "Peru": "PER",
        "Philippines": "PHL",
        "Pitcairn Islands": "PCN",
        "Poland": "POL",
        "Portugal": "PRT",
        "Puerto Rico": "PRI",
        "Qatar": "QAT",
        "Romania": "ROU",
        "Russia": "RUS",
        "Rwanda": "RWA",
        "Réunion": "REU",
        "Samoa": "WSM",
        "San Marino": "SMR",
        "Saudi Arabia": "SAU",
        "Senegal": "SEN",
        "Serbia": "SRB",
        "Seychelles": "SYC",
        "Sierra Leone": "SLE",
        "Singapore": "SGP",
        "Sint Maarten": "SXM",
        "Slovakia": "SVK",
        "Slovenia": "SVN",
        "Solomon Islands": "SLB",
        "Somalia": "SOM",
        "South Africa": "ZAF",
        "South Georgia & South Sandwich Islands": "SGS",
        "South Korea": "KOR",
        "South Sudan": "SSD",
        "Spain": "ESP",
        "Sri Lanka": "LKA",
        "St. Barthélemy": "BLM",
        "St. Helena": "SHN",
        "St. Kitts & Nevis": "KNA",
        "St. Lucia": "LCA",
        "St. Martin": "MAF",
        "St. Pierre & Miquelon": "SPM",
        "St. Vincent & Grenadines": "VCT",
        "Sudan": "SDN",
        "Suriname": "SUR",
        "Svalbard & Jan Mayen": "SJM",
        "Sweden": "SWE",
        "Switzerland": "CHE",
        "Syria": "SYR",
        "São Tomé & Príncipe": "STP",
        "Taiwan": "TWN",
        "Tajikistan": "TJK",
        "Tanzania": "TZA",
        "Thailand": "THA",
        "Timor-Leste": "TLS",
        "Togo": "TGO",
        "Tokelau": "TKL",
        "Tonga": "TON",
        "Trinidad & Tobago": "TTO",
        "Tunisia": "TUN",
        "Turkmenistan": "TKM",
        "Turks & Caicos Islands": "TCA",
        "Tuvalu": "TUV",
        "Türkiye": "TUR",
        "U.S. Outlying Islands": "UMI",
        "U.S. Virgin Islands": "VIR",
        "Uganda": "UGA",
        "Ukraine": "UKR",
        "United Arab Emirates": "ARE",
        "United Kingdom": "GBR",
        "United States": "USA",
        "Uruguay": "URY",
        "Uzbekistan": "UZB",
        "Vanuatu": "VUT",
        "Vatican City": "VAT",
        "Venezuela": "VEN",
        "Vietnam": "VNM",
        "Wallis & Futuna": "WLF",
        "Western Sahara": "ESH",
        "Yemen": "YEM",
        "Zambia": "ZMB",
        "Zimbabwe": "ZWE",
        "Åland Islands": "ALA"
    }

    country_to_url = {
        "Afghanistan": "afghanistan",
        "Albania": "albania",
        "Algeria": "algeria",
        "American Samoa": "american-samoa",
        "Andorra": "andorra",
        "Angola": "angola",
        "Anguilla": "anguilla",
        "Antarctica": "antarctica",
        "Antigua & Barbuda": "antigua-and-barbuda",
        "Argentina": "argentina",
        "Armenia": "armenia",
        "Aruba": "aruba",
        "Australia": "australia",
        "Austria": "austria",
        "Azerbaijan": "azerbaijan",
        "Bahamas": "bahamas",
        "Bahrain": "bahrain",
        "Bangladesh": "bangladesh",
        "Barbados": "barbados",
        "Belarus": "belarus",
        "Belgium": "belgium",
        "Belize": "belize",
        "Benin": "benin",
        "Bermuda": "bermuda",
        "Bhutan": "bhutan",
        "Bolivia": "bolivia",
        "Bosnia & Herzegovina": "bosnia-and-herzegovina",
        "Botswana": "botswana",
        "Bouvet Island": "bouvet-island",
        "Brazil": "brazil",
        "British Indian Ocean Territory": "british-indian-ocean-territory",
        "British Virgin Islands": "british-virgin-islands",
        "Brunei": "brunei-darussalam",
        "Bulgaria": "bulgaria",
        "Burkina Faso": "burkina-faso",
        "Burundi": "burundi",
        "Cambodia": "cambodia",
        "Cameroon": "cameroon",
        "Canada": "canada",
        "Cape Verde": "cape-verde",
        "Caribbean Netherlands": "caribbean-netherlands",
        "Cayman Islands": "cayman-islands",
        "Central African Republic": "central-african-republic",
        "Chad": "chad",
        "Chile": "chile",
        "China": "china",
        "Christmas Island": "christmas-island",
        "Cocos (Keeling) Islands": "cocos-keeling-islands",
        "Colombia": "colombia",
        "Comoros": "comoros",
        "Congo - Brazzaville": "congo-republic-of-the",
        "Congo - Kinshasa": "congo-democratic-republic-of-the",
        "Cook Islands": "cook-islands",
        "Costa Rica": "costa-rica",
        "Croatia": "croatia",
        "Cuba": "cuba",
        "Curaçao": "curacao",
        "Cyprus": "cyprus",
        "Czechia": "czech-republic",
        "Côte d’Ivoire": "cote-d'ivoire",
        "Denmark": "denmark",
        "Djibouti": "djibouti",
        "Dominica": "dominica",
        "Dominican Republic": "dominican-republic",
        "Ecuador": "ecuador",
        "Egypt": "egypt",
        "El Salvador": "el-salvador",
        "Equatorial Guinea": "equatorial-guinea",
        "Eritrea": "eritrea",
        "Estonia": "estonia",
        "Eswatini": "swaziland",
        "Ethiopia": "ethiopia",
        "Falkland Islands (Islas Malvinas)": "falkland-islands-(malvinas)",
        "Faroe Islands": "faroe-islands",
        "Fiji": "fiji",
        "Finland": "finland",
        "France": "france",
        "French Guiana": "french-guiana",
        "French Polynesia": "french-polynesia",
        "French Southern Territories": "french-southern-territories",
        "Gabon": "gabon",
        "Gambia": "gambia",
        "Georgia": "georgia",
        "Germany": "germany",
        "Ghana": "ghana",
        "Gibraltar": "gibraltar",
        "Greece": "greece",
        "Greenland": "greenland",
        "Grenada": "grenada",
        "Guadeloupe": "guadeloupe",
        "Guam": "guam",
        "Guatemala": "guatemala",
        "Guernsey": "guernsey",
        "Guinea": "guinea",
        "Guinea-Bissau": "guinea-bissau",
        "Guyana": "guyana",
        "Haiti": "haiti",
        "Heard & McDonald Islands": "heard-mcdonald-islands",
        "Honduras": "honduras",
        "Hong Kong": "hong-kong",
        "Hungary": "hungary",
        "Iceland": "iceland",
        "India": "india",
        "Indonesia": "indonesia",
        "Iran": "iran",
        "Iraq": "iraq",
        "Ireland": "ireland",
        "Isle of Man": "isle-of-man",
        "Israel": "israel",
        "Italy": "italy",
        "Jamaica": "jamaica",
        "Japan": "japan",
        "Jersey": "jersey",
        "Jordan": "jordan",
        "Kazakhstan": "kazakhstan",
        "Kenya": "kenya",
        "Kiribati": "kiribati",
        "Kosovo": "kosovo",
        "Kuwait": "kuwait",
        "Kyrgyzstan": "kyrgyzstan",
        "Laos": "lao",
        "Latvia": "latvia",
        "Lebanon": "lebanon",
        "Lesotho": "lesotho",
        "Liberia": "liberia",
        "Libya": "libya",
        "Liechtenstein": "liechtenstein",
        "Lithuania": "lithuania",
        "Luxembourg": "luxembourg",
        "Macao": "macao",
        "Madagascar": "madagascar",
        "Malawi": "malawi",
        "Malaysia": "malaysia",
        "Maldives": "maldives",
        "Mali": "mali",
        "Malta": "malta",
        "Marshall Islands": "marshall-islands",
        "Martinique": "martinique",
        "Mauritania": "mauritania",
        "Mauritius": "mauritius",
        "Mayotte": "mayotte",
        "Mexico": "mexico",
        "Micronesia": "micronesia",
        "Moldova": "moldova",
        "Monaco": "monaco",
        "Mongolia": "mongolia",
        "Montenegro": "montenegro",
        "Montserrat": "montserrat",
        "Morocco": "morocco",
        "Mozambique": "mozambique",
        "Myanmar (Burma)": "myanmar",
        "Namibia": "namibia",
        "Nauru": "nauru",
        "Nepal": "nepal",
        "Netherlands": "netherlands",
        "New Caledonia": "new-caledonia",
        "New Zealand": "new-zealand",
        "Nicaragua": "nicaragua",
        "Niger": "niger",
        "Nigeria": "nigeria",
        "Niue": "niue",
        "Norfolk Island": "norfolk-island",
        "North Korea": "north-korea",
        "North Macedonia": "macedonia",
        "Northern Mariana Islands": "northern-mariana-islands",
        "Norway": "norway",
        "Oman": "oman",
        "Pakistan": "pakistan",
        "Palau": "palau",
        "Palestine": "palestinian-territory",
        "Panama": "panama",
        "Papua New Guinea": "papua-new-guinea",
        "Paraguay": "paraguay",
        "Peru": "peru",
        "Philippines": "philippines",
        "Pitcairn Islands": "pitcairn-islands",
        "Poland": "poland",
        "Portugal": "portugal",
        "Puerto Rico": "puerto-rico",
        "Qatar": "qatar",
        "Romania": "romania",
        "Russia": "russian-federation",
        "Rwanda": "rwanda",
        "Réunion": "reunion",
        "Samoa": "samoa",
        "San Marino": "san-marino",
        "Saudi Arabia": "saudi-arabia",
        "Senegal": "senegal",
        "Serbia": "serbia",
        "Seychelles": "seychelles",
        "Sierra Leone": "sierra-leone",
        "Singapore": "singapore",
        "Sint Maarten": "sint-maarten",
        "Slovakia": "slovakia-(slovak-republic)",
        "Slovenia": "slovenia",
        "Solomon Islands": "solomon-islands",
        "Somalia": "somalia",
        "South Africa": "south-africa",
        "South Georgia & South Sandwich Islands": "south-georgia-south-sandwich-islands",
        "South Korea": "south-korea",
        "South Sudan": "south-sudan",
        "Spain": "spain",
        "Sri Lanka": "sri-lanka",
        "St. Barthélemy": "saint-barthelemy",
        "St. Helena": "saint-helena",
        "St. Kitts & Nevis": "saint-kitts-and-nevis",
        "St. Lucia": "saint-lucia",
        "St. Martin": "saint-martin",
        "St. Pierre & Miquelon": "saint-pierre-and-miquelon",
        "St. Vincent & Grenadines": "saint-vincent-and-the-grenadines",
        "Sudan": "sudan",
        "Suriname": "suriname",
        "Svalbard & Jan Mayen": "svalbard-and-jan-mayen",
        "Sweden": "sweden",
        "Switzerland": "switzerland",
        "Syria": "syrian-arab-republic",
        "São Tomé & Príncipe": "sao-tome-and-principe",
        "Taiwan": "taiwan",
        "Tajikistan": "tajikistan",
        "Tanzania": "tanzania",
        "Thailand": "thailand",
        "Timor-Leste": "timor-leste",
        "Togo": "togo",
        "Tokelau": "tokelau",
        "Tonga": "tonga",
        "Trinidad & Tobago": "trinidad-and-tobago",
        "Tunisia": "tunisia",
        "Turkmenistan": "turkmenistan",
        "Turks & Caicos Islands": "turks-and-caicos-islands",
        "Tuvalu": "tuvalu",
        "Türkiye": "turkey",
        "U.S. Outlying Islands": "us-outlying-islands",
        "U.S. Virgin Islands": "virgin-islands-(us)",
        "Uganda": "uganda",
        "Ukraine": "ukraine",
        "United Arab Emirates": "united-arab-emirates",
        "United Kingdom": "united-kingdom",
        "United States": "united-states-of-america",
        "Uruguay": "uruguay",
        "Uzbekistan": "uzbekistan",
        "Vanuatu": "vanuatu",
        "Vatican City (Holy See)": "holy-see-(vatican-city-state)",
        "Venezuela": "venezuela",
        "Vietnam": "viet-nam",
        "Wallis & Futuna": "wallis-and-futuna",
        "Western Sahara": "western-sahara",
        "Yemen": "yemen",
        "Zambia": "zambia",
        "Zimbabwe": "zimbabwe",
        "Åland Islands": "aland-islands"
    }
